#! /bin/bash

if [ ${0#"./"} != "INSTALL" ]
then
	echo "Error : Please go to '3dView' directory. Exit."
	exit 1
fi

### search pyqt4
FILE=`conda list | grep "pyqt "`
if [ -z $FILE ]
then
	conda install pyqt=4
else
	QTVERSION=`echo $FILE | cut -d " " -f 2`
	if [ `echo $QTVERSION | cut -d "." -f 1 ` -ne 4 ]
	then
		### conda uninstall pyqt
		conda install -c anaconda pyqt=4.11.4
	fi
fi

### search mayavi
FILE=`conda list | grep "mayavi "`
if [ -z $FILE ]
then
	conda install mayavi
fi

### bin
mkdir bin
cd bin
ln -fs ../3dplot 3dplot
touch 3dplot.scalar
touch 3dplot.vector
touch 3dplot.gui
echo "#!/bin/bash" >> 3dplot.scalar
echo "if [ -z \$1 ]; then echo 'Usage: 3dplot.scalar [your data file]'; fi" >> 3dplot.scalar
echo "3dplot -t scalar -f $1" >> 3dplot.scalar
echo "#!/bin/bash" >> 3dplot.vector
echo "if [ -z \$1 ]; then echo 'Usage: 3dplot.scalar [your data file]'; fi" >> 3dplot.vector
echo "3dplot -t vector -f $1" >> 3dplot.vector
echo "#!/bin/bash" >> 3dplot.gui
echo "3dplot -t gui" >>3dplot.gui
chmod u+x 3dplot.scalar
chmod u+x 3dplot.vector
chmod u+x 3dplot.gui
chmod u+x 3dplot

### write bash profile
CDIR=`pwd`
echo "export PATH=${CDIR}:\$PATH">>~/.bashrc
